### ISSUE TITLE
Allow pulling ticExecutable from ENV

### ISSUE THREAD

**Issue by RuinTD** [scambier/tic80-typescript#14]
It would be nice if ticExecutable could be retrieved from an environment variable, instead of a config file that would be version controlled. This variable could be named something like `TSC80_EXE`.

**Comment by scambier** [comment]
If you add tic80.exe to your PATH env var, you should be able to run it with this config

```json
{
  "ticExecutable": "tic80.exe", // no path, just the executable name
  "entry": "main.ts",
  "outfile": "build/output.js",
  "minify": false
}
```

Would it solve your issue?

**Comment by RuinTD** [comment]
That would actually. I already have tic80 in my PATH.

**Comment by scambier** [comment]
Neat, I'll close this then :)
