### ISSUE TITLE
Missing option to specify input type

### ISSUE THREAD

**Issue by misteki** [scambier/tic80-typescript#3]
Hello, @scambier ! First of all I'd like to thank you for the tool, I've just started to use it and it's really cool. Great work!

It seems like here's currently no way to specify the input type for the cart in the `tsc80-config.json` file. I had to change it to "mouse" and tried setting it in the file but the metadata field was not being added in the output code.

In my case, I found a workaround: editing line 105 to add the "input" option:

```
preamble: `// title: ${cGame['title']}\n// author: ${cGame['author']}\n// desc: ${cGame['desc']}\n// script: js\n// input: ${cGame['input']}\n`
```

After this, I added the `input` field to the `tsc80-config.json` file with the other metadata and it worked.

I'm not sure how's the contributing status for this project in particular, but if this is indeed a bug, I can send a PR to with this fix if you're alright with it. For now I'll just leave this here.

Best regards!

**Comment by scambier** [comment]
Thanks for the kind words! Please, send me a PR. I'll look at it asap :)

**Comment by misteki** [comment]
https://github.com/scambier/tic80-typescript/pull/4
Let me know if there's anything to change and I'll take another look! :grin:

**Comment by scambier** [comment]
Thanks for the PR. Merged and published 👍 

I've just slightly updated it to keep the "input" option consistent with the others.
